base_url = "https://sepi.me"
compile_sass = false
build_search_index = true
taxonomies = [{ name = "tags", feeds = true }]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/sepisoad"

[[extra.social]]
icon = "git-branch"
name = "SourceHut"
url = "https://sr.ht/~sepisoad"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://x.com/sepisoad"

