SCRIPTS_DIR = scripts
WIP_DIR = wip
TO_PUBLISH_DIR = to-publish
PUBLISHED_DIR = published
PUBLISH_CMD = $(SCRIPTS_DIR)/publish.py
UNPUBLISH_CMD = $(SCRIPTS_DIR)/unpublish.py

export SEPI_BLOG_TO_PUBLISH_DIR = $(TO_PUBLISH_DIR)
export SEPI_BLOG_PUBLISHED_DIR = $(PUBLISHED_DIR)

publish: 
	@python3 $(PUBLISH_CMD)
