#!/usr/bin/env -S deno run --allow-all

import * as U from "./utils/utils.js"

const HOST = "prose.sh"
const toPublishDir = Deno.env.get("SEPI_BLOG_TO_PUBLISH_DIR")
const publishedDir = Deno.env.get("SEPI_BLOG_PUBLISHED_DIR")
const scpCommand = "scp"
const args = Deno.args

if (args.length == 0) {
  console.log("please provide post name using `POST=<NAME>`")
  Deno.exit(1)
}

const post = args[0]

// it seems that there is no way to directly connect to prose.sh via ssh, i mean you can but you cannot run custom ssh commands like listing the files and ...
